import { useState, useEffect } from 'react';


//logic where songs are chosen in coordinance with colors

//possibly consider spotify without an account

//Create an object where key is associated with the color shade. If disliked, it will have an alternative song to pull up that's more epitomizing of that shade

// regular shades get key 'i', light shades get 'ia', dark shades get 'ib'// added as properties for accessibility
    const firstObj = {
            //original
        '1': 'url',
        '2': 'url',
        '3': 'url',
        '4': 'url',
        '5': 'url',
        '6': 'https://www.youtube.com/watch?v=aVbbw1JQZiA&ab_channel=TheRoyalBee',
        '7': 'url',
        '8': 'url',
        '9': 'url',
        '10': 'url',
        '11': 'url',
        '12': 'https://www.youtube.com/watch?v=P3cffdsEXXw',
        '13': 'url',
        '14': 'url',
        '15': 'url',
        '16': 'url',
        '17': 'url',
        '18': 'url',
        '19': 'url',
        '20': 'url',
        '21': 'url',
        '22': 'url',
        '23': 'https://www.youtube.com/watch?v=ChIVsNgzaAo&ab_channel=YellowDaysVEVO',
        '24': 'url',
        '25': 'url',
        '26': 'url',
        '27': 'url',
        '28': 'url',
        '29': 'url',
        '30': 'url',
        '31': 'url',
        '32': 'url',
        '33': 'url',
        '34': 'url',
        '35': 'url',
        '36': 'url',
        '37': 'url',
        '38': 'url',
        '39': 'url',
        '40': 'url',
        '41': 'url',
        '42': 'url',
        '43': 'url',
        '44': 'url',
        '45': 'url',
        '46': 'url',
        '47': 'url',
        '48': 'url',
        '49': 'url',
        '50': 'url',
        '51': 'url',
        '52': 'url',
        '53': 'url',
        '54': 'url',
        '55': 'url',
        '56': 'url',
        '57': 'url',
        '58': 'url',
        '59': 'https://www.youtube.com/watch?v=X2kPLQEFR6Y&ab_channel=COLORS',
        '60': 'url',
        '61': 'url',
        '62': 'url',
        '63': 'url',
        '64': 'url',
        '65': 'url',
        '66': 'url',
        '67': 'url',
        '68': 'url',
            //light colors
        '1a': 'url',
        '2a': 'url',
        '3a': 'url',
        '4a': 'url',
        '5a': 'url',
        '6a': 'url',
        '7a': 'url',
        '8a': 'url',
        '9a': 'url',
        '10a': 'url',
        '11a': 'url',
        '12a': 'url',
        '13a': 'url',
        '14a': 'url',
        '15a': 'url',
        '16a': 'url',
        '17a': 'url',
        '18a': 'url',
        '19a': 'url',
        '20a': 'url',
        '21a': 'url',
        '22a': 'url',
        '23a': 'url',
        '24a': 'https://www.youtube.com/watch?v=tJ_dpxz2lcc&ab_channel=COLORS',
        '25a': 'url',
        '26a': 'url',
        '27a': 'url',
        '28a': 'url',
        '29a': 'url',
        '30a': 'url',
        '31a': 'url',
        '32a': 'url',
        '33a': 'url',
        '34a': 'url',
        '35a': 'url',
        '36a': 'url',
        '37a': 'url',
        '38a': 'url',
        '39a': 'url',
        '40a': 'url',
        '41a': 'url',
        '42a': 'url',
        '43a': 'url',
        '44a': 'url',
        '45a': 'url',
        '46a': 'url',
        '47a': 'url',
        '48a': 'url',
        '49a': 'url',
        '50a': 'url',
        '51a': 'url',
        '52a': 'url',
        '53a': 'url',
        '54a': 'url',
        '55a': 'url',
        '56a': 'url',
        '57a': 'url',
        '58a': 'url',
        '59a': 'url',
        '60a': 'url',
        '61a': 'url',
        '62a': 'url',
        '63a': 'url',
        '64a': 'url',
        '65a': 'url',
        '66a': 'url',
        '67a': 'url',
        '68a': 'url',
            //darkColors
        '1b': 'url',
        '2b': 'url',
        '3b': 'https://www.youtube.com/watch?v=_YOvQNgpfXY&ab_channel=COLORS',
        '4b': 'url',
        '5b': 'https://www.youtube.com/watch?v=hph8xZTq2ZY&ab_channel=NatKingCole-Topic',
        '6b': 'url',
        '7b': 'url',
        '8b': 'url',
        '9b': 'url',
        '10b': 'url',
        '11b': 'url',
        '12b': 'url',
        '13b': 'url',
        '14b': 'url',
        '15b': 'url',
        '16b': 'url',
        '17b': 'url',
        '18b': 'url',
        '19b': 'url',
        '20b': 'url',
        '21b': 'url',
        '22b': 'url',
        '23b': 'url',
        '24b': 'url',
        '25b': 'url',
        '26b': 'url',
        '27b': 'url',
        '28b': 'url',
        '29b': 'url',
        '30b': 'url',
        '31b': 'url',
        '32b': 'url',
        '33b': 'https://www.youtube.com/watch?v=DSbqyWXVDYg&ab_channel=COLORS',
        '34b': 'url',
        '35b': 'url',
        '36b': 'url',
        '37b': 'url',
        '38b': 'url',
        '39b': 'url',
        '40b': 'url',
        '41b': 'url',
        '42b': 'url',
        '43b': 'url',
        '44b': 'url',
        '45b': 'url',
        '46b': 'url',
        '47b': 'url',
        '48b': 'url',
        '49b': 'url',
        '50b': 'url',
        '51b': 'url',
        '52b': 'url',
        '53b': 'url',
        '54b': 'url',
        '55b': 'https://www.youtube.com/watch?v=FmvTyNWB9l4&ab_channel=DavidDeanBurkhart',
        '56b': 'url',
        '57b': 'url',
        '58b': 'url',
        '59b': 'url',
        '60b': 'url',
        '61b': 'url',
        '62b': 'url',
        '63b': 'url',
        '64b': 'url',
        '65b': 'url',
        '66b': 'url',
        '67b': 'url',
        '68b': 'url',
            //lightRow2
        '7c': 'url',
        '8c': 'url',
        '9c': 'https://www.youtube.com/watch?v=7OopD1mdbL8&ab_channel=YellowDays-Topic',
        '10c': 'url',
        '11c': 'url',
        '12c': 'url',
        '13c': 'url',
        '14c': 'url',
        '15c': 'url',
        '16c': 'url',
            //lightRow3
        '6d': 'url',
        '7d': 'url',
        '8d': 'url',
        '9d': 'https://www.youtube.com/watch?v=8GGGliIxpgc&ab_channel=COLORS',
        '10d': 'url',
        '11d': 'url',
        '12d': 'url',
        '13d': 'url',
        '14d': 'url',
            //lightRow4
        '5e': 'url',
        '6e': 'url',
        '7e': 'url',
        '8e': 'url',
        '9e': 'url',
        '10e': 'url',
        '11e': 'url',
        '12e': 'url',
            //darkRow2
        '44f': 'url',
        '45f': 'url',
        '46f': 'url',
        '47f': 'url',
        '48f': 'url',
        '49f': 'url',
        '50f': 'url',
        '51f': 'url',
        '52f': 'url',
        '53f': 'url',
            //darkRow3
        '46g': 'url',
        '47g': 'url',
        '48g': 'url',
        '49g': 'url',
        '50g': 'url',
        '51g': 'url',
        '52g': 'url',
        '53g': 'url',
        '54g': 'url',
            //darkRow4
        '48h': 'url',
        '49h': 'url',
        '50h': 'url',
        '51h': 'url',
        '52h': 'url',
        '53h': 'url',
        '54h': 'url',
        '55h': 'url',
    }

//when button is clicked, it will open a new page in a new tab 
//upon returning back to screen, message will pop up asking for feedback


//create a GET request, where once button is clicked, it will lead to /links, and fromt there it will search for coordinating url, then redirect to page


export default firstObj;